version: "3.7"
services:
  datascience-demo:
    image: jupyter/datascience-notebook:r-4.0.3
    environment:
      - JUPYTER_TOKEN=dp
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: datascience-demo